### PR TITLE
Make the HttpFactory methods non-static

### PR DESCRIPTION
**Pull request by mbabker**
This changes the `HttpFactory` class to use non-static methods which enables the factory to be mocked in applications.

### CODE REVIEW

**Comment by wilsonge** [comment]
I'm not convinced by this. My impression (e.g. http://www.phptherightway.com/pages/Design-Patterns.html) was that factories are supposed to have static methods?

**Comment by mbabker** [comment]
A static method cannot be mocked.  So if I use this factory in my code, my tests must run the actual code of the factory (and inherently its side effects).  Factories can have statics, but there is no best practice stating they must be static.  Our [DatabaseFactory](https://github.com/joomla-framework/database/blob/master/src/DatabaseFactory.php) doesn't use statics for example.

**Comment by mbabker** [comment]
Well...

**Comment by wilsonge** [comment]
I'm honestly not convinced with the reading I've done. But as we're doing it in the Database and Language factories I guess we may as well be consistent.

**Pull request merged**
